// frontend/src/features/charts/TimelineChart.tsx
import { registerables, Chart } from 'chart.js';
import { Line } from 'react-chartjs-2';

Chart.register(...registerables);

interface TimelineChartProps {
  data: Record<string, number>;
}

export function TimelineChart({ data }: TimelineChartProps) {
  const labels = Object.keys(data).sort();
  const values = labels.map(l => data[l]);

  const chartData = {
    labels,
    datasets: [{
      label: 'Log Events',
      data: values,
      borderColor: '#3b82f6',
      backgroundColor: 'rgba(59, 130, 246, 0.1)',
      borderWidth: 2,
      pointRadius: 3,
      pointBackgroundColor: '#3b82f6',
      tension: 0.3,
      fill: true,
    }],
  };

  const options = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { display: false },
      tooltip: {
        mode: 'index' as const,
        intersect: false,
        backgroundColor: 'rgba(15, 23, 42, 0.9)',
        padding: 12,
        titleFont: { size: 14, weight: 'bold' as const },
        bodyFont: { size: 13 },
      }
    },
    scales: {
      y: {
        beginAtZero: true,
        grid: { color: 'rgba(255, 255, 255, 0.05)' },
        ticks: { color: '#94a3b8' }
      },
      x: {
        grid: { display: false },
        ticks: { color: '#94a3b8', maxRotation: 45, minRotation: 45 }
      }
    }
  };

  return (
    <div className="chart-container" style={{ height: '300px' }}>
      <Line data={chartData} options={options} />
    </div>
  );
}

// frontend/src/components/charts/TimelineChart.vue
<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { Chart, registerables } from 'chart.js'
import { useLogStore } from '../../stores/logStore'

Chart.register(...registerables)

const store = useLogStore()
const chartCanvas = ref<HTMLCanvasElement | null>(null)
let chartInstance: Chart | null = null

const updateChart = () => {
  if (!chartCanvas.value) return
  if (chartInstance) chartInstance.destroy()

  const labels = Object.keys(store.timeline)
  const datasets = [
    {
      label: 'ERROR',
      data: labels.map(l => store.timeline[l].ERROR || 0),
      borderColor: '#ef4444',
      backgroundColor: '#ef444422',
      fill: true,
      tension: 0.4
    },
    {
      label: 'WARN',
      data: labels.map(l => store.timeline[l].WARN || 0),
      borderColor: '#f59e0b',
      backgroundColor: '#f59e0b22',
      fill: true,
      tension: 0.4
    }
  ]

  chartInstance = new Chart(chartCanvas.value, {
    type: 'line',
    data: { labels, datasets },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      plugins: {
        legend: { position: 'top', labels: { boxWidth: 10, font: { size: 10 } } },
        tooltip: { mode: 'index', intersect: false }
      },
      scales: {
        y: { beginAtZero: true, grid: { color: '#8882' } },
        x: { grid: { display: false } }
      }
    }
  })
}

onMounted(updateChart)
watch(() => store.timeline, updateChart, { deep: true })
</script>

<template>
  <div class="h-64 relative bg-gray-50 dark:bg-gray-900/40 rounded-xl p-4 border border-gray-100 dark:border-gray-800">
    <canvas ref="chartCanvas"></canvas>
  </div>
</template>
